server.port=8081

blog.work-dir=/www/my-blog

blog.hexo-command=/www/my-blog/node_modules/.bin/hexo

blog.posts-dir=${blog.work-dir}/source/_posts
blog.images-dir=${blog.work-dir}/source/images

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
